In [17]:
import torch
import numpy as np
import pandas as pd
import torch.nn as nn
import matplotlib.pyplot as plt

In [18]:
def embedding_gen(sentence):
    global words
    words = sentence.lower().split(' ')
    word_idx = {elem: idx for idx, elem in enumerate(set(words))}
    idx_only = [idx for idx, _ in enumerate(set(words))]
    global elem_only
    global vocab_size
    vocab_size = len(word_idx)
    embedding_dim = 16
    embedding_layer = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)
    input_tensor = torch.LongTensor(idx_only)
    embedding_tensor = embedding_layer(input_tensor)
    return embedding_tensor

In [19]:
embedding_mat = embedding_gen("If you miss the train I am on you will know I am gone You will hear a whistle blow a hundred miles")
softmax = nn.Softmax()
embedding_mat.shape

torch.Size([17, 16])

In [20]:
embedding_mat

tensor([[-1.6458,  2.6735, -0.6294, -0.9352, -1.7030,  0.6741,  0.8172, -0.4604,
         -0.9493, -1.8822, -1.0437,  0.1781,  0.8973, -0.0976, -0.3789,  1.4148],
        [ 0.8589, -1.5207, -0.5662, -0.2485, -0.4772, -0.1564,  0.6059,  1.0436,
          1.2279,  0.8374, -0.0343, -0.0742,  1.5189, -0.7008,  1.1504, -0.1686],
        [-0.0294,  1.1959,  1.0094, -0.6198,  0.7178, -0.6988,  1.5429, -1.4265,
         -0.5134, -0.6972,  1.0297, -0.8999,  1.7934, -0.6760, -0.7946, -0.3960],
        [-0.7651,  0.2402, -0.7144,  0.3178,  0.9697,  1.3702, -0.8142, -0.3472,
         -0.3337, -0.2528, -0.2846, -0.2778, -1.9415,  0.0288, -0.5864, -0.0477],
        [ 0.9641, -1.2722, -0.6363, -0.3000,  0.8644, -2.0459, -0.1021, -0.9000,
          1.1702,  1.6939,  0.1856,  0.0214, -0.4317,  0.7765, -1.3990,  0.3690],
        [-0.8177,  0.6763,  0.8899,  1.3792, -2.7850,  0.3200,  0.2640,  0.7285,
          0.0619, -0.4340, -0.1591, -0.0916,  2.5104,  1.1186, -1.0749, -2.5823],
        [ 1.0671,  0.5

In [21]:
empty = torch.zeros(embedding_mat.shape)

In [22]:
sum1 = empty+embedding_mat
softmax(sum1/2)

tensor([[0.0247, 0.2138, 0.0410, 0.0352, 0.0240, 0.0787, 0.0845, 0.0446, 0.0349,
         0.0219, 0.0333, 0.0614, 0.0880, 0.0535, 0.0465, 0.1140],
        [0.0798, 0.0243, 0.0392, 0.0459, 0.0409, 0.0481, 0.0704, 0.0876, 0.0960,
         0.0790, 0.0511, 0.0501, 0.1111, 0.0366, 0.0924, 0.0478],
        [0.0535, 0.0987, 0.0899, 0.0398, 0.0777, 0.0383, 0.1174, 0.0266, 0.0420,
         0.0383, 0.0908, 0.0346, 0.1330, 0.0387, 0.0365, 0.0445],
        [0.0444, 0.0733, 0.0455, 0.0762, 0.1056, 0.1290, 0.0433, 0.0547, 0.0550,
         0.0573, 0.0564, 0.0566, 0.0246, 0.0660, 0.0485, 0.0635],
        [0.0929, 0.0304, 0.0417, 0.0494, 0.0883, 0.0206, 0.0545, 0.0366, 0.1029,
         0.1337, 0.0629, 0.0580, 0.0462, 0.0845, 0.0285, 0.0690],
        [0.0342, 0.0721, 0.0802, 0.1024, 0.0128, 0.0603, 0.0587, 0.0740, 0.0530,
         0.0414, 0.0475, 0.0491, 0.1803, 0.0899, 0.0300, 0.0141],
        [0.0863, 0.0669, 0.0589, 0.1029, 0.0417, 0.0749, 0.0466, 0.0641, 0.0224,
         0.0328, 0.0799, 0.0248, 0.12

In [23]:
import torch
import math

def generate_positional_encoding(sequence_length, embedding_dim):
    pe = torch.zeros(sequence_length, embedding_dim)
    position = torch.arange(0, sequence_length, dtype=torch.float).unsqueeze(1)
    div_term = torch.exp(
        torch.arange(0, embedding_dim, 2).float() * (-math.log(10000.0) / embedding_dim)
    )

    pe[:, 0::2] = torch.sin(position * div_term)  # even indices
    pe[:, 1::2] = torch.cos(position * div_term)  # odd indices

    return pe

pos_encoding = generate_positional_encoding(sequence_length=vocab_size, embedding_dim=16)

In [24]:
finna = embedding_mat + pos_encoding
finna

tensor([[-1.6458e+00,  3.6735e+00, -6.2937e-01,  6.4818e-02, -1.7030e+00,
          1.6741e+00,  8.1716e-01,  5.3956e-01, -9.4928e-01, -8.8221e-01,
         -1.0437e+00,  1.1781e+00,  8.9727e-01,  9.0235e-01, -3.7890e-01,
          2.4148e+00],
        [ 1.7004e+00, -9.8039e-01, -2.5521e-01,  7.0189e-01, -3.7741e-01,
          8.3863e-01,  6.3754e-01,  2.0431e+00,  1.2379e+00,  1.8374e+00,
         -3.1149e-02,  9.2584e-01,  1.5199e+00,  2.9920e-01,  1.1507e+00,
          8.3137e-01],
        [ 8.7995e-01,  7.7972e-01,  1.6005e+00,  1.8683e-01,  9.1651e-01,
          2.8128e-01,  1.6061e+00, -4.2849e-01, -4.9344e-01,  3.0260e-01,
          1.0361e+00,  1.0008e-01,  1.7954e+00,  3.2395e-01, -7.9396e-01,
          6.0405e-01],
        [-6.2395e-01, -7.4976e-01,  9.8280e-02,  9.0058e-01,  1.2652e+00,
          2.3256e+00, -7.1945e-01,  6.4834e-01, -3.0373e-01,  7.4678e-01,
         -2.7510e-01,  7.2214e-01, -1.9385e+00,  1.0288e+00, -5.8541e-01,
          9.5228e-01],
        [ 2.0725e-01

In [25]:
Q, K, V = finna, finna, finna

In [26]:
V.shape

torch.Size([17, 16])

In [27]:
import math

w_q = nn.Linear(in_features=16, out_features=16)
w_k = nn.Linear(in_features=16, out_features=16)
w_v = nn.Linear(in_features=16, out_features=16)

Q = w_q(Q)
K = w_k(K)
V = w_k(V)

q_k = torch.matmul(Q, K.transpose(-2, -1))
embedding_dim = 16
q_k = q_k/math.sqrt(embedding_dim)
q_k = softmax(q_k)

q_k_v = torch.matmul(q_k, V)
q_k_v

tensor([[-2.1628e-01,  1.5031e-02, -5.4273e-01,  1.1209e-01, -6.9620e-01,
          3.5219e-01, -4.7813e-01,  1.1999e+00,  2.3619e-01,  5.1547e-01,
          1.1057e+00,  1.5331e-01, -1.3334e-01, -1.6258e-01, -6.7510e-02,
          3.4149e-01],
        [ 3.8895e-01, -2.4875e-01, -6.5384e-01, -4.2624e-01, -2.2442e-01,
         -1.5791e-01, -2.5660e-01,  6.1157e-01,  2.0768e-01,  2.5707e-01,
          6.9736e-01, -3.6542e-01, -2.1826e-01, -1.1950e-02, -1.2797e-01,
         -2.5035e-01],
        [ 5.8866e-01, -1.3555e-01, -4.7411e-01, -1.3321e-01, -5.8339e-02,
         -2.0503e-01,  3.8973e-02,  6.7007e-01,  1.8345e-01,  2.8732e-01,
          4.9910e-01, -3.8971e-01, -9.7846e-02,  1.4826e-02,  1.3171e-01,
         -2.5578e-01],
        [-4.5744e-04, -2.6747e-01, -7.2635e-01, -3.3391e-01, -5.5680e-01,
          1.2621e-01, -3.9390e-01,  7.3259e-01,  1.3276e-01,  3.7888e-01,
          9.7755e-01, -1.0840e-01, -2.0771e-01, -3.3677e-02, -2.2171e-01,
          1.4919e-02],
        [ 2.3719e-01

In [28]:
add_norm_layer1 = q_k_v+finna
layer_norm = nn.LayerNorm(embedding_dim)
add_norm_layer1 = layer_norm(add_norm_layer1)
add_norm_layer1

tensor([[-1.4402,  2.0681, -1.0041, -0.1514, -1.7796,  1.0175, -0.0490,  0.8361,
         -0.7140, -0.4950, -0.2241,  0.5783,  0.2196,  0.2043, -0.5454,  1.4788],
        [ 1.3335, -1.8662, -1.5575, -0.4152, -1.2613, -0.0247, -0.3137,  1.8787,
          0.7129,  1.3385, -0.0386, -0.1406,  0.5741, -0.4040,  0.3051, -0.1208],
        [ 1.2256,  0.0819,  0.7510, -0.7373,  0.3788, -0.7059,  1.4705, -0.4766,
         -1.2417,  0.0067,  1.3180, -1.2135,  1.5432, -0.3417, -1.7304, -0.3286],
        [-0.7160, -1.0624, -0.7193,  0.3340,  0.4590,  1.9960, -1.1471,  1.0519,
         -0.3163,  0.8268,  0.4537,  0.3755, -2.0577,  0.7117, -0.8771,  0.6871],
        [ 0.1331, -1.9035, -0.5403, -0.5868,  0.4616, -1.0629, -0.4061,  0.3189,
          0.8157,  2.0605,  0.6833,  0.4435, -0.8015,  1.1747, -1.4449,  0.6545],
        [-1.2081,  0.2220,  0.6800,  0.5002, -2.0009,  0.3443, -0.0099,  1.3253,
         -0.1295,  0.2755, -0.0625,  0.0283,  1.4939,  1.2787, -1.0610, -1.6763],
        [ 0.5692,  0.7

In [29]:
feed_fwd = nn.Sequential(
    nn.Linear(16, 16),
    nn.Linear(16, 16),
    nn.Linear(16, 16)
)

linear_out = feed_fwd(add_norm_layer1)

out = layer_norm(add_norm_layer1+linear_out)

out

tensor([[-1.7456e+00,  1.7239e+00, -1.0277e+00, -1.7014e-01, -2.0429e+00,
          9.4221e-01,  5.3342e-02,  9.8642e-01, -4.7672e-01, -2.5143e-01,
         -1.0077e-01,  5.7825e-01,  3.7561e-01,  1.5872e-01, -3.8500e-01,
          1.3818e+00],
        [ 1.3473e+00, -1.8149e+00, -1.5083e+00, -5.0057e-01, -1.0945e+00,
          7.4877e-02, -4.8614e-01,  1.8071e+00,  8.8673e-01,  1.6249e+00,
         -1.5034e-01, -1.5522e-01,  2.6155e-01, -2.7933e-01,  1.3451e-01,
         -1.4765e-01],
        [ 1.1296e+00, -9.7838e-02,  8.1153e-01, -7.4696e-01,  2.3133e-01,
         -6.4299e-01,  1.2702e+00, -1.9928e-01, -1.2474e+00,  4.2122e-01,
          1.5488e+00, -1.2517e+00,  1.3148e+00, -2.2471e-01, -1.9381e+00,
         -3.7858e-01],
        [-6.4782e-01, -1.3268e+00, -8.8236e-01,  2.2093e-01,  6.7957e-01,
          1.8177e+00, -1.0435e+00,  1.0793e+00, -3.1871e-02,  1.0966e+00,
          2.5586e-01,  2.6705e-01, -1.9803e+00,  7.8523e-01, -8.7012e-01,
          5.8046e-01],
        [ 2.1015e-01

In [30]:
words

['if',
 'you',
 'miss',
 'the',
 'train',
 'i',
 'am',
 'on',
 'you',
 'will',
 'know',
 'i',
 'am',
 'gone',
 'you',
 'will',
 'hear',
 'a',
 'whistle',
 'blow',
 'a',
 'hundred',
 'miles']

In [31]:
feed_fwd2 = nn.Sequential(
    nn.Linear(16, 16)
)

fin_out = feed_fwd2(out)

probabilities = torch.softmax(fin_out[-1], dim=-1)

#softmax = nn.Softmax(dim=-1)
#fin_out_probs = softmax(fin_out)

In [32]:
next_word = words[probabilities.argmax()]
print(next_word)

the
